In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv("BGT.csv") 
data.head(5)
#print(data)

,T10,T10_T,T10_F,T10_I,L10,L10_T,L10_F,L10_I,H10,H10_T,...,SU12_F,SU12_I,D12,D12_T,D12_F,D12_I,AV12,AV12_T,AV12_F,AV12_I
0,9.3,10,0,0,7.7,8,2,2,8.6,8,...,0,0,8.9,10,0,0,7.8,10,0,0
1,9.1,9,1,1,7.1,9,2,5,8.0,7,...,5,4,8.8,7,1,1,7.6,7,6,4
2,9.4,8,2,2,7.6,10,0,0,9.0,10,...,0,0,9.0,10,0,0,9.0,10,0,0
3,9.3,9,0,9,7.1,9,8,8,8.7,9,...,8,6,8.2,9,7,6,8.3,8,8,9
4,9.3,8,2,3,9.6,6,4,6,8.6,7,...,7,4,9.6,6,4,5,9.4,6,4,5

In [2]:
duc = np.array(data[36:37])[0]
print(duc)

[7.2 8.  2.  2.  6.7 9.  1.  1.  5.6 9.  1.  0.  6.9 8.  2.  1.  8.5 9.
 1.  0.  6.9 7.  3.  2.  7.3 6.  4.  3.  6.  7.  3.  4.  6.8 7.  3.  2.
 6.8 6.  4.  3.  4.2 8.  2.  0.  6.3 7.  3.  2.  7.7 8.  2.  1.  5.7 9.
 1.  1.  7.7 7.  3.  2.  6.1 7.  3.  2.  7.4 7.  3.  1.  7.5 5.  5.  7.
 6.1 5.  5.  8.  7.6 6.  4.  7.  8.7 8.  2.  0.  7.4 6.  4.  4.  7.5 7.
 3.  2.  6.2 7.  3.  3. ]

In [3]:
T10 = duc[0:4]
print(T10)
L10 = duc[4:8]
print(L10)
H10 = duc[8:12]
print(H10)
A10 = np.mean(np.array([T10,L10,H10]),axis=0)
print(A10)

T11 = duc[32:36]
print(T11)
L11 = duc[36:40]
print(L11)
H11 = duc[40:44]
print(H11)
A11 = np.mean(np.array([T11,L11,H11]),axis=0)
print(A11)

T12 = duc[64:68]
print(T12)
L12 = duc[68:72]
print(L12)
H12 = duc[72:76]
print(H12)
A12 = np.mean(np.array([T12,L12,H12]),axis=0)
print(A12)

A = [A10,A11,A12]

[7.2 8.  2.  2. ]
[6.7 9.  1.  1. ]
[5.6 9.  1.  0. ]
[6.5        8.66666667 1.33333333 1.        ]
[6.8 7.  3.  2. ]
[6.8 6.  4.  3. ]
[4.2 8.  2.  0. ]
[5.93333333 7.         3.         1.66666667]
[7.4 7.  3.  1. ]
[7.5 5.  5.  7. ]
[6.1 5.  5.  8. ]
[7.         5.66666667 4.33333333 5.33333333]

In [4]:
T10 = duc[0:4]
print(T10)
L10 = duc[4:8]
print(L10)
A10 = duc[28:32]
print(A10)
A110 = np.mean(np.array([T10,L10,A10]),axis=0)
print(A110)

T11 = duc[32:36]
print(T11)
L11 = duc[36:40]
print(L11)
A11 = duc[60:64]
print(A11)
A111 = np.mean(np.array([T11,L11,A11]),axis=0)
print(A111)

T12 = duc[64:68]
print(T12)
L12 = duc[68:72]
print(L12)
A12 = duc[92:96]
print(A12)
A112 = np.mean(np.array([T12,L12,A12]),axis=0)
print(A112)

A1 = [A110,A111,A112]

[7.2 8.  2.  2. ]
[6.7 9.  1.  1. ]
[6. 7. 3. 4.]
[6.63333333 8.         2.         2.33333333]
[6.8 7.  3.  2. ]
[6.8 6.  4.  3. ]
[6.1 7.  3.  2. ]
[6.56666667 6.66666667 3.33333333 2.33333333]
[7.4 7.  3.  1. ]
[7.5 5.  5.  7. ]
[6.2 7.  3.  3. ]
[7.03333333 6.33333333 3.66666667 3.66666667]

In [5]:
T10 = duc[0:4]
print(T10)
H10 = duc[8:12]
print(H10)
SI10 = duc[12:16]
print(SI10)
B10 = np.mean(np.array([T10,H10,SI10]),axis=0)
print(A10)

T11 = duc[32:36]
print(T11)
H11 = duc[40:44]
print(H11)
SI11 = duc[44:48]
print(SI11)
B11 = np.mean(np.array([T11,H11,SI11]),axis=0)
print(B11)

T12 = duc[64:68]
print(T12)
H12 = duc[72:76]
print(H12)
SI12 = duc[76:80]
print(SI12)
B12 = np.mean(np.array([T12,H12,SI12]),axis=0)
print(B12)

B = [B10,B11,B12]

[7.2 8.  2.  2. ]
[5.6 9.  1.  0. ]
[6.9 8.  2.  1. ]
[6. 7. 3. 4.]
[6.8 7.  3.  2. ]
[4.2 8.  2.  0. ]
[6.3 7.  3.  2. ]
[5.76666667 7.33333333 2.66666667 1.33333333]
[7.4 7.  3.  1. ]
[6.1 5.  5.  8. ]
[7.6 6.  4.  7. ]
[7.03333333 6.         4.         5.33333333]

In [6]:
V10 = duc[16:20]
print(V10)
SU10 = duc[20:24]
print(SU10)
D10 = duc[24:28]
print(D10)
C10 = np.mean(np.array([V10,SU10,D10]),axis=0)
print(A10)

V11 = duc[48:52]
print(V11)
SU11 = duc[52:56]
print(SU11)
D11 = duc[56:60]
print(D11)
C11 = np.mean(np.array([V11,SU11,D11]),axis=0)
print(B11)

V12 = duc[80:84]
print(V12)
SU12 = duc[84:88]
print(SU12)
D12 = duc[88:92]
print(D12)
C12 = np.mean(np.array([V12,SU12,D12]),axis=0)
print(B12)

C = [C10,C11,C12]

[8.5 9.  1.  0. ]
[6.9 7.  3.  2. ]
[7.3 6.  4.  3. ]
[6. 7. 3. 4.]
[7.7 8.  2.  1. ]
[5.7 9.  1.  1. ]
[7.7 7.  3.  2. ]
[5.76666667 7.33333333 2.66666667 1.33333333]
[8.7 8.  2.  0. ]
[7.4 6.  4.  4. ]
[7.5 7.  3.  2. ]
[7.03333333 6.         4.         5.33333333]

In [7]:
T10 = duc[0:4]
print(T10)
V10 = duc[16:20]
print(V10)
A10 = duc[28:32]
print(A10)
DD10 = np.mean(np.array([T10,V10,A10]),axis=0)
print(DD10)

T11 = duc[32:36]
print(T11)
V11 = duc[48:52]
print(V11)
A11 = duc[60:64]
print(A11)
DD11 = np.mean(np.array([T11,V11,A11]),axis=0)
print(DD11)

T12 = duc[64:68]
print(T12)
V12 = duc[80:84]
print(V12)
A12 = duc[92:96]
print(A12)
DD12 = np.mean(np.array([T12,V12,A12]),axis=0)
print(DD12)

D = [DD10,DD11,DD12]

[7.2 8.  2.  2. ]
[8.5 9.  1.  0. ]
[6. 7. 3. 4.]
[7.23333333 8.         2.         2.        ]
[6.8 7.  3.  2. ]
[7.7 8.  2.  1. ]
[6.1 7.  3.  2. ]
[6.86666667 7.33333333 2.66666667 1.66666667]
[7.4 7.  3.  1. ]
[8.7 8.  2.  0. ]
[6.2 7.  3.  3. ]
[7.43333333 7.33333333 2.66666667 1.33333333]

In [8]:
from dm import *
from im import *

def change(A):
    Aok = []
    for i in range(3):
        temp = []
        for j in range(4):
            if j == 0:
                temp.append(A[i][j]/10)
            if j == 1:
                temp.append(A[i][j]/30)
            if j == 2:
                temp.append(A[i][j+1]/30)
            if j == 3:
                temp.append(A[i][j-1]/30)
        Aok.append(temp)
    return(Aok)

matrix = np.array([change(A),change(A1),change(B),change(C),change(D)])
print(matrix)

def rtc(A):
    rtc = []
    for i in range(3):
        temp = []
        for j in range(5):
            temp.append(A[j][i])
        rtc.append(temp)
    return np.array(rtc)
matric = rtc(matrix)

ModuleNotFoundError: No module named 'dm'

In [ ]:
cost = []
mat = rnf(matric,cost)
print(np.array(mat))

In [ ]:
for i in range(13):
    print(np.array(ej(mat,i)))

In [ ]:
for i in range(13):
    print(np.array(cj(mat,i)))

In [ ]:
visual = []
for i in range(13):
    print(np.array(S(mat,i)))
    visual.append(S(mat,i))

In [ ]:
for i in range(13):
    print(np.array(Spos(mat,i)))

In [ ]:
for i in range(13):
    print(np.array(Sneg(mat,i)))

In [ ]:
for i in range(13):
    print(np.array(S(mat,i)))

In [ ]:
for i in range(13):
    print("Similarity no.",i+1,":",np.array(rank(mat,i)))

In [ ]:
 for i in range(13):
    print("Similarity no.",i+1,":",alt(mat,i))

In [ ]:
import matplotlib.pyplot as plt
xaxis = [1,2,3,4,5,6,7,8,9,10,11,12,13]
plt.plot(xaxis,[visual[i][0] for i in range(13)],
         'go-', color='blue', label='A', marker='o')
plt.plot(xaxis,[visual[i][1] for i in range(13)],
         'go-', color='green', label='A1', marker='o')
plt.plot(xaxis,[visual[i][2] for i in range(13)],
         'go-', color='red', label='B', marker='o')
plt.plot(xaxis,[visual[i][3] for i in range(13)],
         'go-', color='cyan', label='C', marker='o')
plt.plot(xaxis,[visual[i][4] for i in range(13)],
         'go-', color='magenta', label='D', marker='o')
plt.xticks(xaxis,["IM1","IM2","IM3","IM4","IM5","IM6","IM7","IM8","IM9","IM10","IM11","IM12","IM13"])
plt.xlabel("Information Measures")
plt.ylabel("Combination Scores")
plt.title("The visualization of combination scores Si and rank of combinations \n using information measures IMi")
figure = plt.gcf()
figure.set_size_inches(10,4.5)
plt.legend(loc='upper center', ncol=5)
plt.savefig('decision making.eps', format='eps')
plt.show()

In [ ]:
# 7.8	7.75	8	Lịch sử	5	Địa lí	7.5	GDCD	9.75
# Khối C: 20.25đ. Khối D: 23.55đ